import { TeachingPoint, getExecutableParts, flattenExecutableParts, WEAVING_TYPE_OPTIONS, PartWeldEnabled, getPartBoundaryInfo } from '../..';
import { enableRobot, RealtimeRobotStatus, startArc, endArc, endWeave, getWeldingConfig, WeldingConfigData, moveToJointPositionNonBlocking, checkMotionDone, createWeldingLog, WeldingLogData, WeldingLogSegment, wireSearchEnd, findDx, findDy, findDz, setWeaveParams, startWeave, arcOn, arcOff, getRobotSettings, moveToCartesianPosition, getInverseKin, arcTraceControl, batchMoveL, BatchMovePoint, getWeldingPartOrder, isApiSuccess } from '../../../../lib';
import { createLogger } from '../../../../lib';
import React from 'react';
import { setWeldingPartOrder } from '../..';
import { WeldingSequenceSettings, SafetySettings } from './weldingCoreTypes';

export const defaultSequenceSettings: WeldingSequenceSettings = {
  touchSensingEnabled: true,
  touchSpeed: 10,
  touchDistance: 100,
  touchOffsetDepth: 5,
  touchApproachOffset: 100,
  touchSensingPointSpeed: 50,
  p1TouchCenter: true,
  p1TouchLeft: true,
  p1TouchRight: true,
  p1TouchBottom: false,
  p2TouchCenter: true,
  p2TouchLeft: true,
  p2TouchRight: true,
  p3TouchCenter: true,
  p3TouchLeft: true,
  p3TouchRight: true,
  p3TouchBottom: true,
  p4TouchCenter: true,
  p4TouchTop: true,
  p4TouchBottom: true,
  p4TouchSide: true,
  p5TouchCenter: true,
  p5TouchTop: true,
  p5TouchBottom: true,
  p6TouchCenter: true,
  p6TouchTop: true,
  p6TouchBottom: true,
  p7TouchCenter: true,
  p7TouchLeft: true,
  p7TouchRight: true,
  p8TouchCenter: true,
  p8TouchLeft: true,
  p8TouchRight: true,
  p9TouchCenter: true,
  p9TouchLeft: true,
  p9TouchRight: true,
  p9TouchBottom: true,
  p10TouchCenter: true,
  p10TouchTop: true,
  p10TouchBottom: true,
  p10TouchSide: true,
  p11TouchCenter: true,
  p11TouchTop: true,
  p11TouchBottom: true,
  p12TouchCenter: true,
  p12TouchTop: true,
  p12TouchBottom: true,
  arcTrackingEnabled: false,
  arcTrackingLeftRight: true,
  arcTrackingUpDown: true,
  arcTrackingKlr: 0.06,
  arcTrackingKud: 0.06,
  arcTrackingStepMaxLr: 5.0,
  arcTrackingStepMaxUd: 5.0,
  arcTrackingSumMaxLr: 30.0,
  arcTrackingSumMaxUd: 30.0,
};
export const defaultSafetySettings: SafetySettings = {
  gasPreFlowTime: 500,
  gasPostFlowTime: 2000,
};
export const mapConfigToSequenceSettings = (config: WeldingConfigData): WeldingSequenceSettings => ({
  touchSensingEnabled: config.touch_sensing_enabled,
  touchSpeed: config.touch_speed,
  touchDistance: config.touch_distance,
  touchOffsetDepth: config.touch_offset_depth,
  touchApproachOffset: config.touch_sensing_approach_offset ?? 100,
  touchSensingPointSpeed: config.touch_sensing_point_speed ?? 50,
  p1TouchCenter: config.p1_touch_center ?? true,
  p1TouchLeft: config.p1_touch_left ?? true,
  p1TouchRight: config.p1_touch_right ?? true,
  p1TouchBottom: config.p1_touch_bottom ?? false,
  p2TouchCenter: config.p2_touch_center ?? true,
  p2TouchLeft: config.p2_touch_left ?? true,
  p2TouchRight: config.p2_touch_right ?? true,
  p3TouchCenter: config.p3_touch_center ?? true,
  p3TouchLeft: config.p3_touch_left ?? true,
  p3TouchRight: config.p3_touch_right ?? true,
  p3TouchBottom: config.p3_touch_bottom ?? true,
  p4TouchCenter: config.p4_touch_center ?? true,
  p4TouchTop: config.p4_touch_top ?? true,
  p4TouchBottom: config.p4_touch_bottom ?? true,
  p4TouchSide: config.p4_touch_side ?? true,
  p5TouchCenter: config.p5_touch_center ?? true,
  p5TouchTop: config.p5_touch_top ?? true,
  p5TouchBottom: config.p5_touch_bottom ?? true,
  p6TouchCenter: config.p6_touch_center ?? true,
  p6TouchTop: config.p6_touch_top ?? true,
  p6TouchBottom: config.p6_touch_bottom ?? true,
  p7TouchCenter: config.p7_touch_center ?? true,
  p7TouchLeft: config.p7_touch_left ?? true,
  p7TouchRight: config.p7_touch_right ?? true,
  p8TouchCenter: config.p8_touch_center ?? true,
  p8TouchLeft: config.p8_touch_left ?? true,
  p8TouchRight: config.p8_touch_right ?? true,
  p9TouchCenter: config.p9_touch_center ?? true,
  p9TouchLeft: config.p9_touch_left ?? true,
  p9TouchRight: config.p9_touch_right ?? true,
  p9TouchBottom: config.p9_touch_bottom ?? true,
  p10TouchCenter: config.p10_touch_center ?? true,
  p10TouchTop: config.p10_touch_top ?? true,
  p10TouchBottom: config.p10_touch_bottom ?? true,
  p10TouchSide: config.p10_touch_side ?? true,
  p11TouchCenter: config.p11_touch_center ?? true,
  p11TouchTop: config.p11_touch_top ?? true,
  p11TouchBottom: config.p11_touch_bottom ?? true,
  p12TouchCenter: config.p12_touch_center ?? true,
  p12TouchTop: config.p12_touch_top ?? true,
  p12TouchBottom: config.p12_touch_bottom ?? true,
  arcTrackingEnabled: config.arc_tracking_enabled,
  arcTrackingLeftRight: config.arc_tracking_left_right,
  arcTrackingUpDown: config.arc_tracking_up_down,
  arcTrackingKlr: config.arc_tracking_klr,
  arcTrackingKud: config.arc_tracking_kud,
  arcTrackingStepMaxLr: config.arc_tracking_step_max_lr,
  arcTrackingStepMaxUd: config.arc_tracking_step_max_ud,
  arcTrackingSumMaxLr: config.arc_tracking_sum_max_lr,
  arcTrackingSumMaxUd: config.arc_tracking_sum_max_ud,
});
export const mapConfigToSafetySettings = (config: WeldingConfigData): SafetySettings => ({
  gasPreFlowTime: config.gas_pre_flow_time,
  gasPostFlowTime: config.gas_post_flow_time,
});
export const loadWeldingSettings = async (): Promise<{ sequence: WeldingSequenceSettings; safety: SafetySettings }> => {
  try {
    const config = await getWeldingConfig();
    return {
      sequence: mapConfigToSequenceSettings(config),
      safety: mapConfigToSafetySettings(config),
    };
  } catch (error) {
    console.warn('용접 설정 로드 실패, 기본값 사용:', error);
    return {
      sequence: defaultSequenceSettings,
      safety: defaultSafetySettings,
    };
  }
};
